# Generated by Django 4.1.13 on 2023-11-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceCode', models.CharField(max_length=15, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('emailAddress', models.CharField(max_length=30)),
                ('signatureStatus', models.CharField(default='N', max_length=1)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
