# Generated by Django 4.1.13 on 2023-11-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatureupload',
            name='signatureImages',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
