# Generated by Django 4.1.13 on 2023-11-29 02:21

from django.db import migrations, models
import image_upload_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0002_signatureupload_signatureimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signatureupload',
            name='signatureImages',
        ),
        migrations.AddField(
            model_name='signatureupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=image_upload_app.models.signature_image_upload_path),
        ),
    ]
