# Generated by Django 4.1.13 on 2023-12-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0003_remove_signatureupload_signatureimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
